[workspace]
members = [
    "agent"
]
exclude = [
    "email-test"
]

# Use the new feature resolver.
# This fixes issues where features from dev-dependencies bleed into regular dependencies.
resolver = "2"
